title: sunuk00.github.io
description: "sunuk00's blog"
logo_img: "/assets/img/Earth.png"
profile_img: "/assets/img/desert_travel.jpg"

# Social Links
email: sunuk2819@gmail.com
github_username: sunuk00
twitter_username: twitter
instagram_username: ssuuuuuu_n
linkedin_username: linkedin
facebook_username: facebook

# External API
giscus_repo: "sunuk00/sunuk00.github.io"
giscus_repoId: "R_kgDORWGGQA"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDORWGGQM4C2-5r"
goatcounter_code: sunuk00
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
future: true  # 미래 날짜 포스트도 빌드에 포함 (기본값 false 시 제외됨)

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/
  - archive/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
  math_engine: mathjax
